<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="1"
            failures="0"
            tests="1">

  <testsuite name="cermati"
    errors="1" failures="0" hostname="" id="" package="cermati" skipped="0"
    tests="1" time="0.005000" timestamp="Sat, 09 Dec 2017 02:10:19 GMT">
  
    <testcase name="QA Engineer Test" classname="cermati" time="0.005000" assertions="0">
    </testcase>
  

  
    <system-err>
        Error while running [Cermati / QA Engineer Test]:

  TypeError: this.timeout is not a function
    at Object.QA Engineer Test (C:\Users\Me\Desktop\cermati\tests\cermati.js:10:7)
    at Module.call (C:\Users\Me\Desktop\cermati\nightwatch\lib\runner\module.js:62:34)
    at C:\Users\Me\Desktop\cermati\nightwatch\lib\runner\testcase.js:70:29
    at _fulfilled (C:\Users\Me\Desktop\cermati\nightwatch\node_modules\q\q.js:834:54)
    at self.promiseDispatch.done (C:\Users\Me\Desktop\cermati\nightwatch\node_modules\q\q.js:863:30)
    at Promise.promise.promiseDispatch (C:\Users\Me\Desktop\cermati\nightwatch\node_modules\q\q.js:796:13)
    at C:\Users\Me\Desktop\cermati\nightwatch\node_modules\q\q.js:556:49
    at runSingle (C:\Users\Me\Desktop\cermati\nightwatch\node_modules\q\q.js:137:13)
    at flush (C:\Users\Me\Desktop\cermati\nightwatch\node_modules\q\q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    </system-err>
  

  
  </testsuite>
</testsuites>
